{% set name = "pycudadecon" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 244a2d0fe3d663aca4c9ded6e51eb39dc9610b9f3a0546fafb9eb9c9595da048

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy
    - cudadecon >=0.7.0
    - tifffile >=0.14.0
    - typing_extensions

test:
  imports:
    - pycudadecon
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/pycudadecon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper for cudaDecon - GPU accelerated 3D deconvolution for microscopy
  description: |
    This package provides a python wrapper and convenience functions for cudadecon,
    a CUDA/C++ implementation of an accelerated Richardson Lucy Deconvolution algorithm.
    It is suitable for general deconvolution of 3D microscopy data, but also has functionality
    for stage-scanning light sheet applications such as Lattice Light Sheet.
  doc_url: https://pycudadecon.readthedocs.io/
  dev_url: https://github.com/tlambert03/pycudadecon

extra:
  recipe-maintainers:
    - tlambert03
    - zbarry
